.gitignore, .idea/misc.xml, .idea/vcs.xml, Makefile, README.md, app/app.iml, app/src/main/AndroidManifest.xml, app/src/main/java/io/github/measurement_kit/app/MainActivity.java, app/src/main/java/io/github/measurement_kit/app/OONITests.java, app/src/main/java/io/github/measurement_kit/app/PortolanTests.java, app/src/main/java/io/github/measurement_kit/app/SyncRunnerService.java, app/src/main/java/io/github/measurement_kit/app/TestCompleteReceiver.java, app/src/main/java/io/github/measurement_kit/app/UnknownTest.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/raw/hosts.txt
This prototype Android application is based on the new repository hosting Measurement Kit JNI libs available at:
https://github.com/bassosimone/measurement-kit-jni-libs
The implementation uses the JNI libs and their interface to run in synchronous mode OONI tests. The basic mechanism to run in background (inside a so-called service) and to notify back the main thread when work is done is already implemented.
Compared to #1, this is significantly simpler in terms of JNI code and interfaces involved.
=> Prototype Android application (try 2)

.idea/compiler.xml, .idea/misc.xml, .idea/vcs.xml, app/app.iml, app/build.gradle, app/src/main/java/io/github/measurement_kit/app/MainActivity.java
The `getDNS()` method asks the device fro DNS resolvers, both for mobile and WiFi. If it fails for some reason, the app will just use the Google DNS instead.
Tested on API 22 (device) and 23 (emulator).
Also changed the compile SDK and target to API 23 and build-tools to 23.0.1.
=> Adding a method to get DNS from device

app/src/main/java/org/openobservatory/ooniprobe/model/NetworkMeasurement.java
Make sure all attributes are initialized, so to ensure that there
are no surprises if the constructor is not called.
It might be that the diff would be correct in C++ and correct and
overkill in Java, but what mattes is that it fixes #76.
Now, there is another pending diff to make sure we have completely
addressed all the issues exposed during #76.
=> NetworkMeasurement.java: initialize all attributes

app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/model/NetworkMeasurement.java
Rather than relying on a shared preference, directly check whether
the file is there or not and, in the latter case, copy it.
Observed during #76. Depends on #78.
=> MainActivity.java: more robust resource copying

README.md
When clicking the header image of the README it redirects to the actual image hosted on github.  It now redirects to the OONI website.
=> Fixes image redirect on README

app/src/main/java/org/openobservatory/ooniprobe/utils/VersionUtils.java
This breaks OONI Backend.
See TheTorProject/ooni-backend#111 and TheTorProject/ooni-sysadmin#164.
=> hotfix(VersionUtility): do not include build number

app/src/main/java/org/openobservatory/ooniprobe/ooniprobeApp.java
As this app uses an application class, Firebase may not initialize itself, So it need to be initialized in the application class.
=> fixing issue#108

.idea/codeStyles/Project.xml, app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java, app/src/main/res/menu/measurement.xml
Fixes https://github.com/ooni/probe/issues/856
- Calling the measurements url every time opening this screen (if json file is on disk) and delete it when published. Having in this case the “status” of the publishing of the measurement in this screen
- Showing different messages if the measurement has been published or not
- Copies the url to clipboard
=> Copy explorer url

app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/NotificationService.java
I moved the `sendNotificaiton` function in a separate class.
This will help the future implementation of automatic testing in background.
I refactored the `sendNotification` function to be as generic as possible and get a text and an icon, while the `notifyTestEnded` function gets a testSuite and from that will generate text and icon.
=> Refactor Notification in a class

app/src/main/java/org/openobservatory/ooniprobe/fragment/measurement/FailedFragment.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java
In iOS we delete JSON and Log file when we re_run a test.
https://github.com/ooni/probe-ios/blob/master/ooniprobe/Model/Database/Measurement.mm#L90
I noticed this doesn't happen in Android and I recreated the same function.
=> Delete Json and Log files on Rerun

app/src/main/java/org/openobservatory/ooniprobe/common/Application.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java
The function to delete Jsons was never called in Android on app start, only when entering the measurement page.
I'm unifying this code with the iOS one, ref:
https://github.com/ooni/probe-ios/blob/master/ooniprobe/Utility/TestUtility.mm#L198
https://github.com/ooni/probe-ios/blob/master/ooniprobe/Utility/TestUtility.mm#L189
https://github.com/ooni/probe-ios/blob/master/ooniprobe/AppDelegate.mm#L179
=> Calling delete json on app start

app/src/main/AndroidManifest.xml
Fixes https://github.com/ooni/probe-android/issues/229 and https://github.com/ooni/probe/issues/865
From
https://stackoverflow.com/questions/12113623/scrollview-is-extremly-slow-on-ics-android-4-0-when-containing-a-long-textview
=> Speeding up textview loading

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/TextActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/ResubmitTask.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java
Fixes https://github.com/ooni/probe/issues/919
I think the three activities (and fragment)
`ResultDetailActivity`
`ResultListFragment`
and `MeasurementDetailActivity`
have some code shared between them, in particular the `ResubmitAsyncTask` and the retry popup.
I tried to refactor some code to remove redundancy but I failed, I'm not confident enough to touch this code at this stage and revamping it would be at least an `effort/L` if not `effort/XL` so I'll open a ticket to track this issue while pushing only basic changes at the moment.
This has been tested “thanks” to this bug https://github.com/ooni/probe/issues/899
=> Upload reason failure

app/src/main/java/org/openobservatory/ooniprobe/common/AppDatabase.java, app/src/main/java/org/openobservatory/ooniprobe/common/Application.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Network.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Result.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Url.java
Fixes a crash with updating tables after we modified the structure in https://github.com/ooni/probe-android/pull/284
I had to create an `AlterTableMigration` and manually tell them to create a new column in the database. 
I used the change to refactor a little bit some classes.
See: https://agrosner.gitbooks.io/dbflow/content/Migrations.html
=> Update db version

app/src/main/java/org/openobservatory/ooniprobe/common/ExceptionManager.java, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java
Fixes https://github.com/ooni/probe/issues/983 
- Created a class called ExceptionManager that imports Crashlytics and sends crash to them.
In this way if we decide to remove Crashlytics and use any other crash reporting system in the code, it will be a one line edit.
=> Created exception utility

app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java
Fixes https://github.com/ooni/probe/issues/918
- The problem was not the modal but the invasive way to refresh the entire preferenceFragment
- I opted for a simpler solution to only refresh the affected field
Ref: https://stackoverflow.com/questions/26335068/how-to-reject-a-change-in-onsharedpreferencechanged-listener
=> Fixing text overlap in preference screen

app/src/main/java/org/openobservatory/ooniprobe/activity/CustomWebsiteActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/OoniRunActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/DashboardFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/measurement/FailedFragment.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/AbstractSuite.java, app/src/main/res/layout/activity_running.xml
Fixes https://github.com/ooni/probe/issues/1093
- Allow `RunningActivity` to get an array of `AbstractSuite` in input, instead of a single one
- Cycle the Array and execute every test sequencially. Quit the screen only when last test is executed
- (re)Load the UX every cycle
=> Add support for running all tests

app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Result.java
Fixes https://github.com/ooni/probe/issues/1153
A new method measurementsSorted has been added that is gonna be used only when displaying website result rows.
=> Sort results in the order they ran

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/Application.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java
Fixes https://github.com/ooni/probe/issues/1212
- Not calling remove log tied to the report file
- Creating a new function that returns all measurement with log files
- Calling this function on app start and removing logs more than 7 days old
=> Remove logs more effectively on app start

app/src/androidTest/java/org/openobservatory/ooniprobe/client/OONIAPIClientTest.java, app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/client/OONIAPIClient.java, app/src/main/java/org/openobservatory/ooniprobe/client/callback/CheckReportIdCallback.java, app/src/main/java/org/openobservatory/ooniprobe/common/Application.java, app/src/main/java/org/openobservatory/ooniprobe/model/api/ApiMeasurement.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java
Fixes https://github.com/ooni/probe/issues/1195
The algorithm would be:
- Query DB for measurement uploaded and with report_id
- Cycle them to get the ones with json file
- UNIQUE the report_id
- Call the api for every report_id
- If true 
- query db to get all measurement with that report_id
- Delete json
=> Check and delete Uploaded report files with the new api

app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Network.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Result.java
Fixes https://github.com/ooni/probe/issues/1240
- Deleting Network table when deleting all tests
- Preventing deletion of the network object if it's in use
- Deleting the network object after the Result is deleted to avoid crash for SQL CONSTRAINTS
=> Fix network count on test deletion

app/build.gradle
@sarathms spotted we were having `com.google.android.gms.ads` and `com.google.firebase.analitycs`
in the app even I never imported them. 
It turns out  they are part of `com.google.firebase:firebase-core` that is now deprecated and not needed:
https://firebase.google.com/support/release-notes/android
=> Remove firebase_core

app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java
Fixes `java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference`
=> Fix crash - null check

app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java, engine/src/main/java/org/openobservatory/engine/Engine.java, engine/src/main/java/org/openobservatory/engine/OONIException.java, engine/src/main/java/org/openobservatory/engine/OONISession.java, engine/src/main/java/org/openobservatory/engine/PESession.java
I've been playing around with countly recently to ensure that the
code is such that exceptions that are trapped by countly are meaningful
enough to us to understand what is going on.
This investigation led me to understand that my original by the book
approach of teaching engine to throw OONIException, as opposed to just
Exception, was probably wrong here.
We're throwing Exception because Go is throwing Exception. Go cannot
do anything much smarter than that here.
By rewrapping the Exception, we're loosing context. We don't see the
cause of error directly in the first line, but further down below such
that we need to click through a specific error to have more info.
What's even more concerning is that countly truncates the stack trace
and the juicy information is dangerously near the …
=> feat(countly): make exceptions more informative

engine/build.gradle
This corresponds to ooni/probe-engine v0.23.0-alpha.2-55-g23a9659.
In my local testing this commit is such that OONI Probe Dev does
not crash anymore as described in https://github.com/ooni/probe/issues/1303.
Because this fixes an issue, I'm marking this commit as a
fix rather than just as a chore.
=> fix: use oonimkall 2021.01.29-110831

app/src/main/java/org/openobservatory/ooniprobe/model/jsonresult/TestKeys.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/RiseupVPN.java
No github issue assigned to the PR
- currently test summaries are shown incorrectly: instead of the number of blocked gateways or bridged connections the user sees "$1%s blocked" 
- this PR fixes it:
Also the condition under which an anomaly was shown was wrong. The second commit fixes that by using a strict rule that riseupvpn is already considered as blocked if one gateway fails. 
In a subsequent step I would like to implement in probe-cli (probe-engine) 2 test result fields that indicate the overall numbers of tested openvpn and obfs4 gateways. Having that would allow us in the client to consider RiseupVPN blocked less strictly by assuming that if at least one working openvpn port has been reached, openvpn is not blocked and if at least one obfs4 port has been reached obfs4 is not …
=> fix test summary formatting for blocked riseupvpn gateways

app/build.gradle
Fixes https://github.com/ooni/probe/issues/1442
- updates retrofit dependencies
- logging-interceptor was not needed to update to fix the crash, but was outdated, too.  In order to avoid any backward compatibility issues that cannot be seen on the first glance I updated the logging-interceptor, too
=> fix app crash when opening MeasurementDetailActivity

app/src/main/java/org/openobservatory/ooniprobe/model/jsonresult/TestKeys.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/RiseupVPN.java
part of https://github.com/ooni/probe/issues/1354
- OONI Probe Android considers a measurement as anomaly if a all gateways supporting a transport are not working (before: if a single gateway fails)
- the change is implemented with the intention to reduce false positives if one gateway is not working for whatever reason. In reality RiseupVPN users will fallback to other gateways and might be able to connect though those.
=> adaptions for riseupvpn measurement v 0.2.0

app/build.gradle, app/src/main/java/org/openobservatory/ooniprobe/common/Application.java, app/src/main/java/org/openobservatory/ooniprobe/common/DateAdapter.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/common/TamperingJsonDeserializer.java, app/src/main/java/org/openobservatory/ooniprobe/di/ActivityComponent.java, app/src/main/java/org/openobservatory/ooniprobe/di/AppComponent.java, app/src/main/java/org/openobservatory/ooniprobe/di/ApplicationModule.java, app/src/main/java/org/openobservatory/ooniprobe/di/ServiceComponent.java, app/src/main/java/org/openobservatory/ooniprobe/di/annotations/ApiUrl.java, app/src/main/java/org/openobservatory/ooniprobe/di/annotations/HeaderInterceptor.java, app/src/main/java/org/openobservatory/ooniprobe/di/annotations/PerActivity.java, app/src/main/java/org/openobservatory/ooniprobe/di/annotations/PerService.java, app/src/test/java/org/openobservatory/ooniprobe/RobolectricAbstractTest.java, app/src/test/java/org/openobservatory/ooniprobe/client/OONIAPIClientTest.java, app/src/test/java/org/openobservatory/ooniprobe/common/ApplicationTest.java, app/src/test/java/org/openobservatory/ooniprobe/di/TestAppComponent.java, app/src/test/java/org/openobservatory/ooniprobe/di/TestAppModule.java, app/src/test/java/org/openobservatory/ooniprobe/di/TestApplication.java
The following PR contains the base files and configuration to install the [Dagger](https://dagger.dev/) compile-time dependency injection framework.
The refactor to include DI in most class's would be huge, since we will be refactoring the [domain logic](https://github.com/ooni/probe/issues/1448) we decided to make those changes incremental for an easier review and safer update.
Small changes can be found already in the _Application.java_ and _PreferenceManager_ class's as well as in the unit test's.
For more information and the official documentation please consult: https://dagger.dev/dev-guide/
=> Dependency injection configuration

README.md, build.gradle, engine/build.gradle
See https://github.com/ooni/probe/issues/1468
While there upgrade the gradle plugin and correct the command
to run a build from command line using `./gradlew`.
Fixes # <issue>
-
-
-
=> chore: use ooni/probe-cli v3.10.0-beta.1

app/src/main/java/org/openobservatory/ooniprobe/common/service/RunTestService.java
* fix(RunTestService.java): pending intent should be IMMUTABLE
The app was crashing because the code did not specify the pending
intent as IMMUTABLE (as far as I understand the stacktrace).
Closes https://github.com/ooni/probe/issues/1897
(This is not my domain of expertise and I think this patch could
and should be better refactored so that we always use a single
factory to create all the intents with the correct flags.)
* fix(RunTestService.java): use factories to avoid repeating ourselves
This diff addresses my previous concern that I fixed the immediate
problem but did not proactively check the rest of the codebase.
Now, `git grep -i pendingintent.newactivity` and
`git grep -i pendingintent.getbroadcast` say that we
have correctly wrapped all the calls.
=> fix(RunTestService.java): pending intent should be IMMUTABLE

app/src/main/java/org/openobservatory/ooniprobe/common/service/RunTestService.java, engine/build.gradle
See https://github.com/ooni/probe/issues/1879
=> chore: use ooni/probe-cli 3.11.0-beta.2 

.gitignore, README.md, engine-experimental/.gitignore, engine-experimental/README.md, engine-experimental/build.gradle, engine/README.md, engine/build.gradle, settings.gradle
Say you have built an experimental `oonimkall.aar` artifact
from the `ooni/probe-cli` repo at whatever commit in whatever
branch. Say you want to test such an artifact against the
current `master` of the `ooni/probe-android` app.
How do you achieve that?
1. copy `oonimkall.aar` inside `./engine-experimental`;
2. `./gradlew assembleExperimentalFullRelease` (remember to
set `ANDROID_SDK_ROOT`);
3. locate the `apk` using `find` and then use `adb install` to
install such an APK on your phone.
I'm doing this work as part of https://github.com/ooni/probe/issues/1917
to facilitate quickly testing of `torsf` and co-developing together
the `probe-cli` and `probe-android` repositories.
=> feat: allow one to build and test a oonimkall.aar

app/src/main/res/drawable/rounded_corner.xml
Fixes # ooni/probe#1919
- Changed background color for proxy indicator on various modes.
| Light Mode  | Dark Mode |
| ------------- | ------------- |
| ![Screenshot_20220203_165721](https://user-images.githubusercontent.com/17911892/152379783-e87202e2-78eb-4c0d-8f1b-ec0961639f2c.png)  | ![Screenshot_20220203_165751](https://user-images.githubusercontent.com/17911892/152379763-97a5329b-cfa2-4862-ad14-5c41eda15c94.png)  |
=> Changed background color for proxy indicator on various modes.

app/src/main/java/org/openobservatory/ooniprobe/common/ReachabilityManager.java
Fixes  ooni/probe#1901
- Update `ReachabilityManager.getNetworkType` to return `vpn` if VPN connection is in use.
=> Mark measurements coming from a VPN with a special annotation

LICENSE
The measurement engine has been relicensed to GPLv3 in
https://github.com/ooni/probe-cli/pull/446.
We forgot to update the mobile repositories to the same
license when we relicensed the engine.
Let's do this now!
Part of https://github.com/ooni/probe/issues/1909
=> chore: relicense android to GPLv3

app/src/main/java/org/openobservatory/ooniprobe/activity/CustomWebsiteActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/OoniRunActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/di/FragmentComponent.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/DashboardFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/measurement/FailedFragment.java, app/src/main/res/values/strings.xml, app/src/main/res/values/untraslatable.xml, app/src/main/res/xml/preferences_global.xml
Fixes https://github.com/ooni/probe/issues/2015 
Replaces https://github.com/ooni/probe-android/pull/497 
-  Update service `RunningActivity` to only show modal when `VPN` and `warn_vpn_in_use` are enabled.
-  Update VPN warning modal to add option to `Always Run`
| Light Theme      | Dark Theme |
| ----------- | ----------- |
| ![Screenshot_20220314_145729](https://user-images.githubusercontent.com/17911892/158188319-d666e745-576d-453d-b932-6acbeeb47dcb.png) | ![Screenshot_20220314_145709](https://user-images.githubusercontent.com/17911892/158188403-e6b58682-9b13-4573-9e99-07bfee5530c9.png) |
|  ![Screenshot_20220314_145847](https://user-images.githubusercontent.com/17911892/158188569-c2fd54b2-ef68-474a-bd89-456e791b559f.png) | …
=> Do not display VPN warnings when VPN warnings option is disabled

app/src/main/java/org/openobservatory/ooniprobe/activity/AbstractActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/Application.java, app/src/main/java/org/openobservatory/ooniprobe/common/LocaleUtils.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java, app/src/main/res/values/strings.xml, app/src/main/res/values/untraslatable.xml, app/src/main/res/xml/preferences_global.xml
Fixes  https://github.com/ooni/probe/issues/1933 on android
- Add Language preference to `Advanced Settings`.
- Add `LocaleUtils` to hold localization helper methods.
- Update `PreferenceFragment.onSharedPreferenceChanged` to exit and prompt user to close app to reapply settings.
| .  | . | .  | . |
| ----------- | ----------- |----------- | ----------- |
|  ![Screenshot_20220318_230922](https://user-images.githubusercontent.com/17911892/159091262-960ff1af-bcdd-4515-9006-d39c8ac92fed.png)  | ![Screenshot_20220318_230911](https://user-images.githubusercontent.com/17911892/159091267-c6426489-b75d-48bc-8975-d8f4abfd1f92.png) | ![Screenshot_20220318_230821](https://user-images.githubusercontent.com/17911892/159091268-b9a856e6-b8a5-495d-a8d2-91109cf70fa2.png) | …
=> Add support for in-app language selection

app/src/main/java/org/openobservatory/ooniprobe/test/suite/ExperimentalSuite.java, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
Fixes  https://github.com/ooni/probe/issues/2038
- Change the colour resource in light/dark mode
| Light | Dark | Light | Dark |
| ----------- | ----------- | ----------- | ----------- |
| ![Screenshot_20220321_142904](https://user-images.githubusercontent.com/17911892/159271487-fd65c41e-ab47-4cdb-8eec-cc717e213b6f.png)      | ![Screenshot_20220321_142841](https://user-images.githubusercontent.com/17911892/159271496-d861c642-b032-4786-85b6-ff5ba2a09950.png)  | ![Screenshot_20220321_142809](https://user-images.githubusercontent.com/17911892/159271502-774917a2-d79e-4fe2-8de3-10080a5b2f52.png) | ![Screenshot_20220321_142738](https://user-images.githubusercontent.com/17911892/159271511-1f95b915-f38d-4d85-9e60-e46892e0e0c3.png) |
=> fix background color in the experimental test group animation

app/src/main/AndroidManifest.xml, app/src/main/java/org/openobservatory/ooniprobe/activity/OoniRunActivity.java, app/src/main/java/org/openobservatory/ooniprobe/domain/GetTestSuite.java
Fixes https://github.com/ooni/probe/issues/1997
- Add `intent-filter` for view to capture text share and validate `URL`
- Update existing methods related to running tests in `OoniRunActivity` and `GetTestSuite` to use `List<String>` and not `Attribute`
| .      | . |
| ----------- | ----------- |
|  ![Screenshot_20220329_202437](https://user-images.githubusercontent.com/17911892/160692360-53b3cb3e-a1a6-4b35-9c67-fd79244b5825.png) |  ![Screenshot_20220329_202454](https://user-images.githubusercontent.com/17911892/160692336-7e0090ad-c417-42e3-90a0-605422858343.png)   |
=> Add support for sharing a link to the OONI Probe app

app/src/main/java/org/openobservatory/ooniprobe/common/DialogUtil.java, app/src/main/java/org/openobservatory/ooniprobe/common/ResubmitTask.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java, app/src/main/res/values/styles.xml
Fixes  https://github.com/ooni/probe/issues/1252
- Add `DialogUtil.makeProgressDialog` to create dialog.
- Modified `ResubmitTask` constructor call to super [`NetworkProgressAsyncTask`](https://github.com/xanscale/LocalhostToolkit/blob/19.05.01/app/src/main/java/localhost/toolkit/os/NetworkProgressAsyncTask.java#L13) ,  [`ProgressAsyncTask`](https://github.com/xanscale/LocalhostToolkit/blob/19.05.01/app/src/main/java/localhost/toolkit/os/ProgressAsyncTask.java#L20-L24) to disable dialog.
- Initialize progress dialog and receive progress in `ResubmitTask` as required.
| . | . | . |
| --- | --- | --- |
| ![Screenshot_20220402_190910](https://user-images.githubusercontent.com/17911892/161396080-5adfb11b-edae-41a0-bfc1-6e8aedce8cee.png) | …
=> Add cancel dialog to upload progress

app/build.gradle, app/src/androidTest/AndroidManifest.xml, app/src/debug/AndroidManifest.xml, app/src/full/AndroidManifest.xml, app/src/main/AndroidManifest.xml, app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/service/ServiceUtil.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/ExperimentalSuite.java, build.gradle, engine/build.gradle, engine/src/main/AndroidManifest.xml, gradle/wrapper/gradle-wrapper.properties
This pull request starts adding support for ooni/probe-cli v3.15.1.
See https://github.com/ooni/probe/issues/2100
While there, upgrade gradle and apply recommended settings.
=> chore: use ooni/probe-cli v3.15.1

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/AppDatabase.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/measurement/FailedFragment.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java
Fixes  https://github.com/ooni/probe/issues/851
-  Update `Measurement`  table to add  `rerun_network` column.
- Annotate  `AbstractTest` before rerun is triggered.
- Capture network during `status.geoip_lookup` event and save to class instance.
- Update measurement to include new network during `measurement` probe-enigine evennt
=> Wrong ASN displayed in successful results of a re-run failed test when different network is selected

app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java
Fixes  https://github.com/ooni/probe/issues/2156
- Remove code path blocking activity exit and ensure test is still running.
=> Fix: `RunningActivity` back button

app/src/main/java/org/openobservatory/ooniprobe/common/service/ServiceUtil.java, app/src/main/java/org/openobservatory/ooniprobe/domain/GenerateAutoRunServiceSuite.java, app/src/main/java/org/openobservatory/ooniprobe/model/settings/Settings.java, app/src/main/java/org/openobservatory/ooniprobe/receiver/TestRunBroadRequestReceiver.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/AbstractSuite.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/CircumventionSuite.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/ExperimentalSuite.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/InstantMessagingSuite.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/MiddleBoxesSuite.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/PerformanceSuite.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/WebsitesSuite.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Dash.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Experimental.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/FacebookMessenger.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/HttpHeaderFieldManipulation.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/HttpInvalidRequestLine.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Ndt.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Psiphon.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/RiseupVPN.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Signal.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Telegram.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Tor.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/WebConnectivity.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Whatsapp.java
Fixes https://github.com/ooni/probe/issues/2167
- Update `AbstractSuite` to include `boolean autoRun`
- Update `getTestList` to set origin of tests to `autorun` when appropriate.
- Pass `isAutoRun` to `AbstractTest` settings when `AbstractTest.run` and use that to update `Settings.Options` appropriately.
=> Feat: append `-unattended` to software_name used for unattended runs

app/build.gradle, engine/build.gradle
This release updates dependencies and fixes a crash on mobile
devices: https://github.com/ooni/probe/issues/2173.
=> chore: use ooni/probe-cli@v3.15.2

app/src/main/java/org/openobservatory/ooniprobe/common/service/RunTestService.java, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java
Fixes  https://github.com/ooni/probe/issues/2195 , https://github.com/ooni/probe/issues/2187
- Register `BroadcastReceiver` for `org.openobservatory.ooniprobe.activity.RunningActivity` in `RunTestService` , used to update  notifications and call `stopSelf` where neccessary.
=> Fix `NullPointerException ` related to `WeakReference<RunTestService>`

app/src/androidTest/java/org/openobservatory/ooniprobe/test/WebConnectivityTest.java, app/src/main/java/org/openobservatory/ooniprobe/activity/OoniRunActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/service/RunTestService.java, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java, app/src/test/java/org/openobservatory/ooniprobe/test/TestAsyncTaskTest.java, app/src/test/java/org/openobservatory/ooniprobe/test/suite/ExperimentalSuiteTest.java
Fixes https://github.com/ooni/probe/issues/2386
- Capture changes in the experimental test structure.
- Updates `TestAsyncTask` constructor arguments.
- Ignores `TestAsyncTaskTest.runTest_withProgress` (Come up with a better way to test the scenario).
- Update `OoniRunActivity.loadScreen` to better capture all test scenarios.
- Updated `WebConnectivityTest.CLIENT_URL`.
=> Fixes broke tests

app/src/main/java/org/openobservatory/ooniprobe/common/Application.java, app/src/main/java/org/openobservatory/ooniprobe/common/ResubmitTask.java, app/src/main/java/org/openobservatory/ooniprobe/domain/MeasurementsManager.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Result.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java, app/src/sharedTest/java/org/openobservatory/ooniprobe/factory/MeasurementFactory.java, app/src/test/java/org/openobservatory/ooniprobe/client/OONIAPIClientTest.java, app/src/test/java/org/openobservatory/ooniprobe/domain/MeasurementsManagerTest.java, app/src/test/java/org/openobservatory/ooniprobe/model/database/MeasurementTest.java, build.gradle
Fixes https://github.com/ooni/probe/issues/2162
=> update measurement-log retention policy

app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java
Fixes  https://github.com/ooni/probe/issues/2346
- Explicitly set text direction for `OverviewActivity` description text view if language is RTL given that the localization is dynamic.
| Before | After |
|-|-|
| ![Screenshot_20230117_120245](https://user-images.githubusercontent.com/17911892/212884482-a3609c36-4131-4e6a-8cf4-d2a15a4ce4f2.png) | ![Screenshot_20230117_120508](https://user-images.githubusercontent.com/17911892/212884520-e54ec6a3-7907-4307-94ca-1d8b34268bff.png) |
=> RTL support on Experimental Test overview description

app/src/fdroid/res/xml/preferences_global.xml, app/src/main/res/xml/preferences_global.xml
Fixes  https://github.com/ooni/probe/issues/2204
- Remove `riseupvpn` from settings.
=> OONI Probe Mobile remove RiseupVPN option in Settings

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/domain/GetTestSuite.java, app/src/main/res/menu/share.xml
Fixes https://github.com/ooni/probe/issues/2367
- Add `reRun` menu option `MeasurementDetailActivity`  when the Measurement is anomalous.
- Run test with the single URL that presets the anomaly
|.|.|
|-|-|
| ![Screenshot_20230112_132910](https://user-images.githubusercontent.com/17911892/212067627-c1e03633-ee9b-413d-bb3c-598f690b0daf.png) | ![Screenshot_20230112_132943](https://user-images.githubusercontent.com/17911892/212067666-c9bb389f-4b0d-498f-a32f-527acc07bbf3.png)|
| ![Screenshot_20230112_133022](https://user-images.githubusercontent.com/17911892/212067709-184a261b-5562-43a9-b5cf-04348a33416d.png) | ![Screenshot_20230112_132958](https://user-images.githubusercontent.com/17911892/212067696-d65c08eb-929c-45fd-b2d1-e9287447f548.png) |
| …
=> Add support to OONI Probe for re-testing of an anomalous URL

app/src/main/java/org/openobservatory/ooniprobe/model/database/Network.java, app/src/main/res/layout/fragment_result_head_detail.xml, app/src/main/res/layout/item_circumvention.xml, app/src/main/res/layout/item_experimental.xml, app/src/main/res/layout/item_instantmessaging.xml, app/src/main/res/layout/item_middleboxes.xml, app/src/main/res/layout/item_performance.xml, app/src/main/res/layout/item_websites.xml, app/src/test/java/org/openobservatory/ooniprobe/model/database/NetworkTest.java
Fixes https://github.com/ooni/probe/issues/2371
- Change `Network.toString` format to match `Cogetel Online, Cambodia, ISP (AS23673 )`
- Add elipses to test list  `asnName` TextView
|.|.|.|
|-|-|-|
| ![Screenshot_20230207_090606](https://user-images.githubusercontent.com/17911892/217193039-e35e121a-fdf2-47e5-b0a1-e05792748fca.png) | ![Screenshot_20230207_091333](https://user-images.githubusercontent.com/17911892/217193099-c2b0a5f9-22a3-4b0e-947d-9f9c6f631c8a.png) | ![Screenshot_20230207_092228](https://user-images.githubusercontent.com/17911892/217193150-365376c9-40a9-4682-b681-7e1de146a733.png) |
=> Human friendly network identification with Autonomous System Numbers (ASN)

app/build.gradle, app/src/main/java/org/openobservatory/ooniprobe/model/jsonresult/EventResult.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java, engine/build.gradle
While there, log the actual log message rather than the serialized JSON, which simplifies reading logs.
=> chore: use ooni/probe-cli@v3.17.1

app/build.gradle
- Modified `build.gradle` to to include `versionNameSuffix` for `beta` and `experimental` versions
=> Added version suffix for beta and experimental to match pattern `x.x.x-beta.x`

app/build.gradle, engine/build.gradle
This diff updates to probe-cli@v3.17.4, which includes the following fixes:
* 🚧 feat: use 2023-06 geoip database https://github.com/ooni/probe-cli/commit/56438f2c1cdffb2f8c7d9f583615e4764e0f9a7b
* 🐛 fix(oohelperd): use cookiejar for HTTP measurements https://github.com/ooni/probe-cli/commit/a3af5542986e314a4e766d36078bedbae5c977ef
* 🐛 fix: use openssl-1.1.1u https://github.com/ooni/probe-cli/commit/325a8412999b001f4913ab5c522ed6402c9d78fe
Related issue: https://github.com/ooni/probe/issues/2485.
=> chore: update to ooni/probe-cli@v3.17.4

app/src/main/AndroidManifest.xml
Fixes  https://github.com/ooni/probe/issues/2330
- declare permission `POST_NOTIFICATIONS` to enable notifications to show on Android 11+ devices
=> fix: Android OONI Notification Constantly wakes up mobile screen.

app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java, app/src/main/res/menu/website_categories.xml
Fixes https://github.com/ooni/probe/issues/2465
- Add menu option to select/unselect all website categories
|.|.|
|-|-|
| ![Screenshot_20230615_083450](https://github.com/ooni/probe-android/assets/17911892/6eb56a91-5bf4-4c0f-864a-f8ed4caeaee7) | ![Screenshot_20230615_083511](https://github.com/ooni/probe-android/assets/17911892/89fd2d45-40b1-4d90-9480-861bc52b047f) |
=> Feat: Add a setting that enables users to easily enable and disable all website categories

app/src/main/java/org/openobservatory/ooniprobe/adapters/LogRecyclerViewAdapter.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceGlobalFragment.java, applogger/src/main/java/org/openobservatory/applogger/LogType.kt, applogger/src/main/java/org/openobservatory/applogger/LoggerManager.kt
Fixes  https://github.com/ooni/probe/issues/2508
- Migrate from `Butterknife` to `ViewBinding` in `PreferenceGlobalFragment`, moving fragment replacement to `onStart` to prevent race condition
-  Adds safe defaults for instances where logs are empty cased by debug logs.
=> fix: log view crashes when using debug logs

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/service/RunTestService.java
Fixes  https://github.com/ooni/probe/issues/2507
- Update app to request for `android.permission.POST_NOTIFICATIONS` in `MainActivity`
- Prepare `RunTestService` to run on android API `34`
=> fix: missing prompt to enable notifications

app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java
=> Chore: Update `OverviewActivity` to `ViewBinding`

app/src/main/java/org/openobservatory/ooniprobe/fragment/DashboardFragment.java, app/src/main/java/org/openobservatory/ooniprobe/item/TestsuiteItem.java
=> Chore: Update `DashboardFragment` to `ViewBinding`

app/src/main/java/org/openobservatory/ooniprobe/activity/TextActivity.java
=> Chore: Update `TextActivity` to `ViewBinding`

app/src/main/java/org/openobservatory/ooniprobe/fragment/ProgressFragment.java
=> Chore: Update `ProgressFragment` to `ViewBinding`

app/src/main/java/org/openobservatory/ooniprobe/fragment/onboarding/Onboarding1Fragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/onboarding/Onboarding2Fragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/onboarding/Onboarding3Fragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/onboarding/OnboardingAutoTestFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/onboarding/OnboardingCrashFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/onboarding/OnboardingDialogPopquizFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/onboarding/OnboardingDialogWarningFragment.java
=> Chore: Update Onboarding fragments to `ViewBinding`

app/src/main/java/org/openobservatory/ooniprobe/activity/ProxyActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/ProxyProtocol.java, app/src/main/java/org/openobservatory/ooniprobe/common/ProxySettings.java, app/src/main/res/layout/activity_proxy.xml, app/src/main/res/values/untraslatable.xml
Fixes  https://github.com/ooni/probe/issues/2561
- Update support for socks proxy to use dropdown for selecting a scheme.
- Update code to save and retrieve the various proxies.
=> Feat: Add support for `http` and `https` proxies

app/build.gradle, app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/ProxyActivity.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/measurement/PsiphonFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/measurement/RiseupVPNFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/measurement/TorFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/measurement/WebConnectivityFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/onboarding/Onboarding3Fragment.java, gradle/libs.versions.toml
- Update from `ru.noties:markwon:2.0.1` to `io.noties.markwon:core:4.6.2`
- Update required API usage.
Note: This update will allow us to use the `markwon` [plugin system](https://noties.io/Markwon/docs/v4/core/plugins.html) to implement additional functionality like the [Read more](https://github.com/noties/Markwon/blob/v4.6.2/app-sample/src/main/java/io/noties/markwon/app/samples/ReadMorePluginSample.java#L48C7-L208) which is added as part of the new designs.
=> Chore: Update from `ru.noties:markwon:2.0.1` to `io.noties.markwon:core:4.6.2`

app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java
Fixes: https://github.com/ooni/probe/issues/2644
- Check if the test is `unattended` before setting a timeout.
- Reference issue: https://github.com/ooni/probe/issues/2644
=> Fix: Timeout for unatted tests.

.github/workflows/firebase-app-distribution.yml
Fixes https://github.com/ooni/probe/issues/2643
- Adds Credentials to the repo
- Add a new workflow file for Firebase App Distribution which publishes debug `apk`.
=> Chore: Add support for sending build to firebase app distribution

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/runtests/adapter/RunTestsExpandableListViewAdapter.kt, app/src/main/res/layout/activity_result_detail.xml
- Update `MeasurementDetailActivity` to check test names when displaying performance results.
- Update `ResultDetailActivity` to use colour of results in themes setup and use `Experimental` test names to determine where to navigate when the measurement is clicked.
=> fix: Match result colors with descriptor theme color

app/src/main/java/org/openobservatory/ooniprobe/common/Application.java, app/src/main/java/org/openobservatory/ooniprobe/common/TestStateRepository.kt, app/src/main/java/org/openobservatory/ooniprobe/fragment/DashboardFragment.kt, app/src/main/java/org/openobservatory/ooniprobe/fragment/ProgressFragment.kt, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java, app/src/main/res/drawable/progress_blue.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_measurement_detail.xml, app/src/main/res/layout/activity_overview.xml, app/src/main/res/layout/activity_result_detail.xml, app/src/main/res/layout/fragment_dashboard.xml, app/src/main/res/layout/fragment_progress.xml
- Update `ProgressFragment` to match design spec.
- Introduce `TestStateRepository` to reliably store the state of the running test (UI not currently displayed cannot receive events from BroadcasrReciever).
- Update `DashboardFragment` to replace `run` button with `ProgressFragment`  when tests are running.
| Dark Mode with `vpn` banner| Light Mode with `vpn` banner|
|-|-|
| ![Screenshot_20240226_123849](https://github.com/ooni/probe-android/assets/17911892/8496ea6e-40ab-4510-a218-0773211f6eee) | ![Screenshot_20240226_124029](https://github.com/ooni/probe-android/assets/17911892/c0df87d8-6c37-4592-8cd7-503f52d34c84) |
| Dark mode with no `vpn` | Light mode with no `vpn` |
| ![Screenshot_20240226_124728](https://github.com/ooni/probe-android/assets/17911892/bf981e43-bcf5-442e-9df4-03bffd952 …
=> fix: Updated `ProgressFragment` and its position on dashboard.

app/src/androidTest/java/org/openobservatory/ooniprobe/ui/OoniRunActivityTest.java
Fixes  https://github.com/ooni/probe/issues/2587
- Update the OONIRunActivityTest to run pre-release QA checks
-  Web Connectivity
-  no inputs: https://run.ooni.io/nettest?tn=web_connectivity&mv=2.0.0 
- empty inputs: https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%5D%7D&mv=2.0.0 
-  partial input: https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22http%3A%2F%2F%22%5D%7D&mv=2.0.0
-  valid URLs: https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22http%3A%2F%2Fwww.google.it%22%2C%22https%3A%2F%2Frun.ooni.io%2F%22%5D%7D&mv=2.0.0 
-  with malformed URL content: https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22http%3A%2F%2Fwww.google.it%22%2C%22https%3A%2F%2Frun.ooni.io&mv=2.0.0
-  NDT: …
=> feat: Extend OONI Run v1 Test cases to capture all pre-release QA checks

app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/adddescriptor/AddDescriptorActivity.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/adddescriptor/AddDescriptorViewModel.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/oonirun/OoniRunV2Activity.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/runtests/adapter/RunTestsExpandableListViewAdapter.kt, app/src/main/java/org/openobservatory/ooniprobe/adapters/DashboardAdapter.kt, app/src/main/java/org/openobservatory/ooniprobe/common/OONIDescriptor.kt, app/src/main/java/org/openobservatory/ooniprobe/common/worker/UpdateDescriptorsWorker.kt, app/src/main/java/org/openobservatory/ooniprobe/model/database/TestDescriptor.kt, app/src/main/res/layout/activity_add_descriptor.xml
- Check if `worker` has started before actually displaying progress.
- Add color to `AddDescriptorActivity` icon
- End `OoniRunV2Activity` when descriptor cannot be fetched.
- Update `InstalledDescriptor` to use preference prefix properly.
=> fix: run-test preferences and color inconsitencies

app/src/main/java/org/openobservatory/ooniprobe/activity/runtests/RunTestsActivity.kt
- Fixes  https://github.com/ooni/run/issues/142
- Add `Toast` where no test is selected
|.|.|
|-|-|
| ![Screenshot_20240320_173337](https://github.com/ooni/probe-android/assets/17911892/ee2bb49d-7411-4807-91b0-1a2445aa5ba4) | ![Screenshot_20240320_173411](https://github.com/ooni/probe-android/assets/17911892/b4c4986a-f608-483a-b8c4-4223e9892f4b) |
=> chore (OONI Run V2): Add missing error message when no tests are selected

app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/overview/OverviewTestsExpandableListViewAdapter.kt, app/src/main/java/org/openobservatory/ooniprobe/fragment/ConfirmDialogFragment.kt
- Fixes  https://github.com/ooni/run/issues/147
- Add `ConfirmDialogFragment` on button click litenner
|.|.|
|-|-|
| ![Screenshot_20240320_165115](https://github.com/ooni/probe-android/assets/17911892/cf1b3894-e866-4be0-889d-d530fd4469f0) | ![Screenshot_20240320_165136](https://github.com/ooni/probe-android/assets/17911892/55b6d363-b5af-4496-a165-894c93e29139)|
=> feat: (OONI Run v2) Add Link uninstall warning

app/src/main/java/org/openobservatory/ooniprobe/adapters/DashboardAdapter.kt, app/src/main/java/org/openobservatory/ooniprobe/common/OONIDescriptor.kt, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManagerExtension.kt, app/src/main/java/org/openobservatory/ooniprobe/fragment/dashboard/DashboardViewModel.kt
- Fixes https://github.com/ooni/run/issues/141 , https://github.com/ooni/run/issues/143
- Remove `isEnabled` from the dashboard.
- Change `OONITests.WEBSITES` preferences
=> feat: (OONI Run v2) Web connectivity tests always appears selected, even if deselected

app/src/main/java/org/openobservatory/ooniprobe/activity/runtests/RunTestsActivity.kt
Fixes https://github.com/ooni/run/issues/161
- Filter out expired tests when launching `RunTestsActivity`
|.|.|
|-|-|
| ![Screenshot_20240411_081232](https://github.com/ooni/probe-android/assets/17911892/2ffc19b1-08c7-4dcd-9bc0-914171c747c1) | ![Screenshot_20240411_081249](https://github.com/ooni/probe-android/assets/17911892/9e07f07d-e3ce-4674-b20d-a36a998c7d01) |
=> feat(OONI Run v2): Filter out expired tests when launching `RunTestsActivity`

app/build.gradle, app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/adddescriptor/AddDescriptorActivity.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/reviewdescriptorupdates/AvailableUpdatesViewModel.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/reviewdescriptorupdates/ReviewDescriptorUpdatesActivity.kt, app/src/main/java/org/openobservatory/ooniprobe/adapters/DashboardAdapter.kt, app/src/main/java/org/openobservatory/ooniprobe/fragment/DashboardFragment.kt, app/src/main/java/org/openobservatory/ooniprobe/fragment/dashboard/DashboardViewModel.kt, app/src/main/java/org/openobservatory/ooniprobe/model/database/Result.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/TestDescriptor.kt, app/src/main/res/drawable/warning_amber.xml, app/src/main/res/layout/activity_overview.xml, app/src/main/res/layout/item_testsuite.xml, app/src/main/res/layout/updated_tag.xml
- Introduce `AvailableUpdatesViewModel` to store cancelled updates across the application instance.
- Show the `updated` badge based on the availability of the descriptor in `AvailableUpdatesViewModel`
|.|.|
|-|-|
| ![Screenshot_20240508_090940](https://github.com/ooni/probe-android/assets/17911892/fffe9487-5836-4742-a571-d8530ed3d647) | ![Screenshot_20240508_090952](https://github.com/ooni/probe-android/assets/17911892/c4b990ed-8cdc-4635-a637-6349a71e9356) |
=> feat (OONI Run v2): Add support for updated badge

app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/overview/OverviewViewModel.kt, app/src/main/java/org/openobservatory/ooniprobe/common/TestDescriptorManager.kt, app/src/main/java/org/openobservatory/ooniprobe/common/worker/UpdateDescriptorsWorker.kt, app/src/main/java/org/openobservatory/ooniprobe/fragment/DashboardFragment.kt, app/src/main/java/org/openobservatory/ooniprobe/fragment/dashboard/DashboardViewModel.kt, app/src/main/res/layout/activity_overview.xml
Fixes  https://github.com/ooni/run/issues/167 , https://github.com/ooni/run/issues/168
- Call `Url.checkExistingUrl` when updating descriptor, fixes https://github.com/ooni/run/issues/168
- Restructure `OverviewActivity` to ensure UI is updated when updates are accepted.
-
=> feat: Refine updates changing the fetch interval and behaviour.

app/build.gradle, app/src/main/res/values-es/strings.xml, app/src/main/res/values-th/strings.xml
Part of https://github.com/ooni/probe/issues/2738
- Update translations.
- Update version code and name.
=> chore(release): prepare app for `v3.8.8` release

app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java
Fixes  https://github.com/ooni/run/issues/180
- Remove dependence on `ENQUEUED` state and use progress to display the `ProgressBar`
=> fix: possible delay start for `WorkRequest` causing UI inconsistency

.github/workflows/validate.yml
Fixes https://github.com/ooni/probe/issues/2779
- Enable hardware accelerated emulators (KVM) as suggested on https://github.com/ReactiveCircus/android-emulator-runner
- Switch the emulator profile to example given on https://github.com/ReactiveCircus/android-emulator-runner
- Remove the `disable-animations` because the default value is already `true`
=> Fix: Instrumented tests on CI

app/build.gradle, app/src/main/java/org/openobservatory/ooniprobe/common/service/RunTestService.java, app/src/test/java/org/openobservatory/ooniprobe/model/database/ResultTest.java, gradle.properties, gradle/libs.versions.toml
I haven't created a ticket for these changes.
- Fix `ResultTest.getLastResult` by ensuring that the first result really has a start_time before the second result
- Fix `BuildConfig` warning by changing to the new configuration
- Remove the `mockito-inline` dependency, since it's no longer needed for Mockito 5
- This PR started as an attempt to fix https://github.com/ooni/probe/issues/2777 but I wasn't able to do it yet
=> Fix flaky ResultTest and build config warnings

.github/workflows/validate.yml
- Replace `wzieba/Firebase-Distribution-Github-Action` with scripts managed by the team
https://github.com/ooni/probe/issues/2643
=> chore: update github workflow to remove third party dependency

.github/workflows/validate.yml
- Apply cache suggestions from https://github.com/ReactiveCircus/android-emulator-runner to improve the instrumented tests time. It's currently taking 9-10 minutes.
- Added more `setup-gradle` steps to further use gradle cache too. Those need to be merged to `master` to work.
=> Cache AVD to improve instrumented tests time

app/src/androidTest/java/org/openobservatory/ooniprobe/ui/MainActivityWebsitesTest.java, app/src/androidTest/java/org/openobservatory/ooniprobe/ui/RunningActivityTest.java, app/src/androidTest/java/org/openobservatory/ooniprobe/ui/resultdetails/CircumventionTest.java, app/src/androidTest/java/org/openobservatory/ooniprobe/ui/resultdetails/InstantMessagingTest.java, app/src/androidTest/java/org/openobservatory/ooniprobe/ui/resultdetails/PerformanceTest.java, app/src/androidTest/java/org/openobservatory/ooniprobe/ui/resultdetails/TestResultsMainScreenTest.java, app/src/androidTest/java/org/openobservatory/ooniprobe/ui/resultdetails/WebsitesTest.java, app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/ExperimentalSuite.java, app/src/test/java/org/openobservatory/ooniprobe/test/suite/ExperimentalSuiteTest.java, gradle/libs.versions.toml
Fixes  https://github.com/ooni/probe/issues/2795
- Add OpenVPN to experimental tests/
- Update tests to reflect change in experimental test.
=> chore: add openvpn to experimental suite

app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManagerExtension.kt
This assumes that the user hasn't changed the preference for running `ndt` and `dash` in autorun.
=> fix: change default for `ndt` and `dash` in autorun

app/src/main/java/org/openobservatory/ooniprobe/activity/OnboardingActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/PreferenceActivity.java, app/src/main/res/layout/activity_add_descriptor.xml, app/src/main/res/layout/activity_blank.xml, app/src/main/res/layout/activity_customwebsite.xml, app/src/main/res/layout/activity_info.xml, app/src/main/res/layout/activity_log.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_measurement_detail.xml, app/src/main/res/layout/activity_oonirun.xml, app/src/main/res/layout/activity_overview.xml, app/src/main/res/layout/activity_proxy.xml, app/src/main/res/layout/activity_result_detail.xml, app/src/main/res/layout/activity_review_descriptor_updates.xml, app/src/main/res/layout/activity_run_tests.xml, app/src/main/res/layout/activity_running.xml, gradle/libs.versions.toml
Fixes https://github.com/ooni/probe/issues/2833
- Update layouts to add `android:fitsSystemWindows="true"`.
- Add layouts forpreference and onboarding screen.
- Update dependencies.
=> fix: multiple reports of floating header issues on some Android devices.
