ooni/probe-android

Makefile, app/src/main/java/io/github/measurement_kit/app/SyncRunnerService.java
<strike>Ongoing work **not ready to be merged yet**, based on measurement-kit/measurement-kit-android#2.</strike>
This can now be tested and merged since the above mentioned pull request was merged.
=> Write last report and logs on device

README.md
Suggested by and discussed with @Lymphatus.
=> README.md: explain how to import my gpg key

app/build.gradle, app/src/main/java/org/openobservatory/ooniprobe/activity/RunTestActivity.java
Needs more testing, but I guess it's ok
Closes #112
=> Solving #112

description/source.xlf
@lorenzoPrimi @hellais I've updated/edited the app description (the same has been done for f-droid).
=> Edited the mobile app description

.idea/misc.xml, app/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
@lorenzoPrimi I've also updated Android!
=> Update to MK v0.8.0-beta.1-1

app/build.gradle, app/src/full/java/org/openobservatory/ooniprobe/common/FirebaseMessagingService.java, app/src/main/java/org/openobservatory/ooniprobe/activity/InfoActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/MKOrchestraSettings.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Network.java, app/src/main/java/org/openobservatory/ooniprobe/model/settings/Settings.java, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java
=> update MK to version 0.10.1-1-android.2

app/build.gradle, app/src/main/java/org/openobservatory/ooniprobe/common/MKCollectorResubmitTask.java, app/src/main/java/org/openobservatory/ooniprobe/common/MKOrchestraTask.java, app/src/main/java/org/openobservatory/ooniprobe/model/settings/Settings.java, app/src/main/res/values/untraslatable.xml
=> Added software_name and software_version to mkcollector

app/src/main/java/org/openobservatory/ooniprobe/item/InstantMessagingItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/MeasurementItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/MeasurementPerfItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/MiddleboxesItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/PerformanceItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/WebsiteItem.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java
- Adding double checks for is_uploaded and report_id (where missing)
- Unique function spread across all the classes
=> Fix cloud icon not appearing

app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/MKCollectorResubmitTask.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java
=> Prevent rerun and not done measurements to get uploaded

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/MKCollectorResubmitTask.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java
=> added retry upload alert

app/src/full/java/org/openobservatory/ooniprobe/common/FirebaseMessagingService.java, app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/OrchestraTask.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Network.java, app/src/main/java/org/openobservatory/ooniprobe/model/settings/Settings.java, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java
=> Rename MKTask, et al., to fix broken travis build

.github/ISSUE_TEMPLATE/release-qa-check-list.md
Xref: https://github.com/ooni/probe/issues/862
=> Add issue template for release QA

app/src/main/java/org/openobservatory/ooniprobe/common/ResubmitTask.java
Fixes https://github.com/ooni/probe/issues/864
- Add a toast when upload complete
=> Toast on completion

app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java
Functions that check every uploaded measurements with still report file on disk
Relative iOS pr https://github.com/ooni/probe-ios/pull/292
Like in iOS the relative unit test will be done when using this function to delete these tests with json
=> Tests with json

app/src/androidTest/java/org/openobservatory/ooniprobe/client/OONIAPIClientTest.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Result.java
Things the reviewer should do:
=> Delete the files of measurements on explorer

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java, app/src/main/res/menu/measurement_nolog.xml
=> Remove "View log" button when there is no log file

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/res/menu/measurement_nolog.xml
Fixes https://github.com/ooni/probe-ios/issues/306
- Refactor menu https://android.i-visionblog.com/android-changing-menu-items-at-run-time-48970f0cf1b7
- Hide option on runtime
-
=> refactor menu

app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java
=> Fixing max_runtime not being parsed

app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java, app/src/main/java/org/openobservatory/ooniprobe/item/TestsuiteItem.java, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/AbstractSuite.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/WebConnectivity.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ca/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fa/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sq/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/untraslatable.xml, app/src/main/res/xml/preferences_websites.xml
Fixes https://github.com/ooni/probe/issues/893
Missing the string, at the moment it say 0 as runtime
=> Allow to enable/disable max_runtime

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/ResubmitTask.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java
Fixes https://github.com/ooni/probe/issues/915
=> Show number of failed uploads

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java, build.gradle
Fixes https://github.com/ooni/probe/issues/928
- When we call delete log function we check if a week passed between the test date and the actual date
=> Remove logs weekly

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/TextActivity.java, app/src/main/res/layout/text.xml
- Migrated the get date from file methods inside the Log Activity to prevent `TransactionTooLargeException `
=> Move the opening file function in TextActivity

app/src/main/java/org/openobservatory/ooniprobe/fragment/DashboardFragment.java
Putting Middlebox before Performance
=> Reorder test list

app/src/main/res/layout/fragment_measurement_dash.xml, app/src/main/res/layout/fragment_measurement_header_ndt.xml, app/src/main/res/layout/fragment_measurement_ndt.xml
Fixes https://github.com/ooni/probe/issues/906
- Adding negative margins
=> Adding negative margins for performance test results

app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java, app/src/main/java/org/openobservatory/ooniprobe/item/FailedItem.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Result.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java, app/src/main/res/layout/item_failed.xml
Fixes https://github.com/ooni/probe/issues/855
=> Bouncer failure logic

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ca/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fa/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sq/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
Fixes https://github.com/ooni/probe/issues/980
=> Remove Toast.WillBeAvailable

app/src/main/java/org/openobservatory/ooniprobe/activity/CustomWebsiteActivity.java
Fixes https://github.com/ooni/probe/issues/982
=> Custom websites: sanitize input

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/TextActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/Application.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java
Fixes https://github.com/ooni/probe/issues/1034 and https://github.com/ooni/probe/issues/1035
- Adding input to API call
- Fixing the `ms` not being ms but seconds
- Preventing okHttp to autoretry on 503
- Commenting code to call delete function on start
- Adding custom user agent
=> Adding input to api call

app/src/main/java/org/openobservatory/ooniprobe/item/FailedItem.java
=> Remove (null) in case of null failure_msg

app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java
Add string parameter in retest url modal
=> Add string parameter in retest url

app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/res/values/strings.xml
Fixes https://github.com/ooni/probe/issues/1020
- Adding indeterminate progress bar on start
- Adding `Calculate ETA` string on time remaining on start
=> Test running screen improve during URLs download

app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java, app/src/main/res/values/untraslatable.xml
Fixes https://github.com/ooni/probe/issues/1073
- Refactoring algorithm
=> Fixing preference checks

app/src/fdroid/res/xml/preferences_global.xml, app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/res/xml/preferences_global.xml
Fixes https://github.com/ooni/probe/issues/1090
=> Remove Notification from preferences

engine/build.gradle
Part of https://github.com/ooni/probe-engine/issues/504
=> engine/build.gradle: pin to org.ooni:oonimkall:2020.04.22-151604

app/build.gradle
Fixing the versionName that was preventing results to be uploaded with MK
=> Fixing versionName

app/src/fdroid/res/xml/preferences_global.xml, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java, app/src/main/res/xml/preferences_global.xml
Fixes https://github.com/ooni/probe/issues/1105
- Remove `include_cc` from settings screen
- Always sending `TRUE`
=> Remove Country Code setting

app/src/main/java/org/openobservatory/ooniprobe/model/settings/Settings.java
Fixes https://github.com/ooni/probe/issues/1112
=> Check include_asn setting before sending network_type

app/src/main/res/layout/item_instantmessaging.xml, app/src/main/res/layout/item_middleboxes.xml, app/src/main/res/layout/item_performance.xml, app/src/main/res/layout/item_websites.xml
Fixes some visual issues with the new icons
=> Fixing icons size

app/src/main/java/org/openobservatory/ooniprobe/activity/CustomWebsiteActivity.java
Fixes https://github.com/ooni/probe/issues/1154
=> Update website count

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/resultHeader/ResultHeaderMiddleboxFragment.java, app/src/main/java/org/openobservatory/ooniprobe/item/FailedItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/MeasurementPerfItem.java, app/src/main/res/drawable/test_middle_boxes_small.xml, app/src/main/res/drawable/test_middle_boxes_white.xml, app/src/main/res/layout/item_failed.xml
UI fix for the middlebox row inside Performance test
=> New middleboxes row

app/src/main/res/layout/activity_measurement_detail.xml, app/src/main/res/layout/fragment_measurement_whatsapp.xml
Fixes https://github.com/ooni/probe/issues/1159
- Reducing margins and add better padding
=> Add space between whatsapp test result columns

app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Result.java
Fixes https://github.com/ooni/probe/issues/1162
- Add fixed sorting algorithm
=> Fix the order of results

app/src/main/res/layout/item_middleboxes.xml
Fixes https://github.com/ooni/probe/issues/1165
=> Fix middlebox icon size

app/src/main/java/org/openobservatory/ooniprobe/item/WebsiteItem.java, app/src/main/res/layout/item_websites.xml
Fixes showing wrong number in the website items
Note:
Not tested (changed in a text editor)
=> website item - change available number to total

app/src/main/java/org/openobservatory/ooniprobe/activity/BrowserActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/NotificationDialogActivity.java
Fixes https://github.com/ooni/probe/issues/834
=> Deprecate ooni browser

app/src/main/java/org/openobservatory/ooniprobe/model/settings/Settings.java
In preparation to https://github.com/ooni/probe-engine/issues/671
=> Setting tmp and asset directory

build.gradle
Fixes https://github.com/ooni/probe/issues/1191
=> Use JCenter for probe-engine's oonimkall

app/src/main/java/org/openobservatory/ooniprobe/model/settings/Settings.java, engine/build.gradle
See https://github.com/ooni/probe-engine/releases/tag/v0.13.0
Part of https://github.com/ooni/probe-engine/issues/673
=> Use probe-engine v0.13.0

engine/build.gradle
Part of https://github.com/ooni/probe/issues/1178
=> Use ooni/probe-engine@v0.13.1

engine/build.gradle
=> Update engine and mk

engine/build.gradle
To be merged after the pending release
=> Use ooni/probe-engine v0.14.0

app/src/androidTest/java/org/openobservatory/ooniprobe/model/jsonresult/TestKeysTest.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/measurement/HeaderNdtFragment.java, app/src/main/java/org/openobservatory/ooniprobe/model/jsonresult/TestKeys.java
Fixes https://github.com/ooni/probe/issues/1215
- Changing the test targeting `Advanced` to the new `Summary` class
- Renaming `getServer` function in `getServerDetails` for consistency
=> Update unit tests

app/src/fdroid/res/xml/preferences_global.xml, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java, app/src/main/java/org/openobservatory/ooniprobe/model/settings/Settings.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Whatsapp.java, app/src/main/res/values/untraslatable.xml, app/src/main/res/xml/preferences_global.xml
Fixes https://github.com/ooni/probe/issues/1226
=> Remove test_whatsapp_extensive option

app/src/fdroid/res/xml/preferences_global.xml, app/src/main/res/drawable/privacy.xml, app/src/main/res/xml/preferences_global.xml
Fixes https://github.com/ooni/probe/issues/1229
=> Adding privacy icon to settings

README.md
Also part of https://github.com/ooni/probe-engine/issues/893
=> README.md: point badge to GHA

.github/workflows/emulator.yml, app/src/androidTest/java/org/openobservatory/ooniprobe/client/OONIAPIClientTest.java, app/src/androidTest/java/org/openobservatory/ooniprobe/client/OONIOrchestraClientTest.java, app/src/androidTest/java/org/openobservatory/ooniprobe/test/WebConnectivityTest.java, app/src/main/java/org/openobservatory/ooniprobe/common/Application.java, app/src/main/java/org/openobservatory/ooniprobe/model/settings/Settings.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java
Part of https://github.com/ooni/backend/issues/450
=> Created integration test for WebConnectivity and API

app/build.gradle
Part of  https://github.com/ooni/probe/issues/1255
=> Update build.gradle to fix Fdroid

app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java
Fixes https://github.com/ooni/probe/issues/1254
=> Print progress messages

.github/workflows/emulator.yml
Noticed when thinking about https://github.com/ooni/probe/issues/1255 and specifically about how to test f-droid.
=> workflows/emulator.yml: also run on PRs

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/res/menu/measurement.xml
Fixes https://github.com/ooni/probe/issues/1176
=> Add share explorer url menu option

engine/build.gradle
See https://github.com/ooni/probe-engine/issues/972
=> update: probe-engine v0.19.0

app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java
Fixes https://github.com/ooni/probe/issues/1277
=> Adding DeleteAllTests event

app/build.gradle
Fixes https://github.com/ooni/probe/issues/1249
=> Update Countly to 20.11.0

app/src/fdroid/res/xml/preferences_global.xml, app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java, app/src/main/res/values/untraslatable.xml, app/src/main/res/xml/preferences_global.xml
Fixes https://github.com/ooni/probe/issues/1260
=> Restructure sharing settings

app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java
Fixes https://github.com/ooni/probe/issues/1266
=> Handle failure.resolver_lookup case

engine/build.gradle
See https://github.com/ooni/probe-engine/issues/1004
=> chore: use ooni/probe-engine@v0.20.1

app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java
Fixes https://github.com/ooni/probe/issues/1273
=> Adding loader on test deletion

app/src/main/java/org/openobservatory/ooniprobe/activity/CustomWebsiteActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/OoniRunActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/TextActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/CountlyManager.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/DashboardFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java
Fixes https://github.com/ooni/probe/issues/1286
+ breakdown by type "TestOverview_websites"
+ breakdown by type "TestSummary_websites"
+ breakdown by type "TestDetails_dash"
=> Logging views manually

app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Result.java
=> Fixing database query that prevented json deletion

app/src/main/java/org/openobservatory/ooniprobe/model/settings/Settings.java, engine/build.gradle
See https://github.com/ooni/probe-engine/issues/1043
=> chore: use ooni/probe-engine v0.21.0

app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java
Fixes https://github.com/ooni/probe/issues/1306
- Requesting notifications every 5 app opening
- Add don't ask again button
=> Re-ask for asking push notification permission

app/build.gradle, app/src/full/AndroidManifest.xml, app/src/full/java/org/openobservatory/ooniprobe/common/FirebaseMessagingService.java
Fixes https://github.com/ooni/probe/issues/1307
=> Tapping on notification doesn't open OONI Run or the app

app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java
Fixes https://github.com/ooni/probe/issues/1296
The scenario when I'm on wifi and I lose wifi to go on LTE triggers `onLost(Network network)` so it interrupt the test.
On the other hand the scenario when I'm on LTE and I get WiFi
```
2020-12-10 09:33:09.831 16191-16457/org.openobservatory.ooniprobe.dev I/vvv: connected to LTE
2020-12-10 09:33:21.022 16191-16457/org.openobservatory.ooniprobe.dev I/vvv: connected to WIFI
```
doesn't trigger `onLost` but only `onAvailable`, in this case I won't feel comfortable to interrupt the test
=> Add connectivity change monitoring

app/src/main/java/org/openobservatory/ooniprobe/common/Application.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Dash.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/FacebookMessenger.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/HttpHeaderFieldManipulation.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/HttpInvalidRequestLine.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Ndt.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Psiphon.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/RiseupVPN.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Telegram.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Tor.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/WebConnectivity.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Whatsapp.java
Fixes https://github.com/ooni/probe/issues/1325
=> Removing redundant mk_name

engine/build.gradle
See https://github.com/ooni/probe-engine/issues/1125
=> chore: use ooni/probe-engine 0.22.0

.github/workflows/build.yml, .github/workflows/emulator.yml
Be sure we build both the stable and fdroid release
=> Build different flavors

app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java
Fixes https://github.com/ooni/probe/issues/1329
=> Handle out of space Error

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/ResubmitTask.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java
Fixes https://github.com/ooni/probe/issues/1345
and https://github.com/ooni/probe/issues/1302
=> Fixing snackbar and reuploading issue

app/src/main/java/org/openobservatory/ooniprobe/activity/CustomWebsiteActivity.java, app/src/main/res/layout/edittext_url.xml
Fixes https://github.com/ooni/probe/issues/1344
=> Prevent to run test when custom url doesn't start with http or https prefix

app/build.gradle, app/src/main/java/org/openobservatory/ooniprobe/common/service/ServiceUtil.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/AbstractSuite.java
=> Bumping minSdkVersion to 24

app/src/main/java/org/openobservatory/ooniprobe/common/ReachabilityManager.java, app/src/main/java/org/openobservatory/ooniprobe/common/service/ServiceUtil.java
Fixes https://github.com/ooni/probe/issues/1460
=> Add VPN check

app/src/main/res/layout/activity_proxy.xml
Fixes https://github.com/ooni/probe/issues/1499
=> Update colors for night mode

app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java
Fixes https://github.com/ooni/probe/issues/1504
=> Automated test ask modal

app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/res/layout/activity_running.xml
Fixes https://github.com/ooni/probe/issues/1423
=> Possibility to minimize the running activity while a test is running

app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/res/drawable/rounded_corner.xml, app/src/main/res/layout/activity_running.xml
Fixes https://github.com/ooni/probe/issues/1500
=> Display that a proxy is being used in the OONI Probe app

app/src/main/java/org/openobservatory/ooniprobe/activity/OoniRunActivity.java, app/src/main/java/org/openobservatory/ooniprobe/item/MeasurementItem.java
Fixes #1706
- Prevent app to crash when an url is null
- Validate url in OONI Run
=> validate URLs

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/res/layout/activity_measurement_detail.xml, app/src/main/res/menu/share.xml
Fixes https://github.com/ooni/probe/issues/1160 and https://github.com/ooni/probe/issues/1756 and https://github.com/ooni/probe/issues/1757
=> Test details UI with new buttons

app/src/main/res/layout/activity_result_detail.xml, app/src/main/res/layout/fragment_result_list.xml
Fixes https://github.com/ooni/probe/issues/1298
=> Add logo to test results

app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/res/layout/activity_measurement_detail.xml, app/src/main/res/values-el/strings.xml
Fixes https://github.com/ooni/probe/issues/1755
=> Adding methodology paragraph

app/build.gradle, app/src/fdroid/java/org/openobservatory/ooniprobe/common/ThirdPartyServices.java, app/src/full/java/org/openobservatory/ooniprobe/common/ThirdPartyServices.java, app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java
Fixes https://github.com/ooni/probe/issues/1237
Using google libraries
https://developer.android.com/guide/playcore/in-app-updates
https://developer.android.com/guide/playcore/in-app-updates/kotlin-java
=> Adding google library for update

app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java
Checking result for null
Fixes https://github.com/ooni/probe/issues/1788
=> Fix NullPointerException

app/src/main/java/org/openobservatory/ooniprobe/common/MapUtility.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/RiseupVPN.java
Fixes https://github.com/ooni/probe/issues/1787
Solution from https://stackoverflow.com/questions/58408832/nosuchmethoderror-no-interface-method-getordefaultljava-lang-objectljava-lang
=>  RuntimeException after RiseupVPN finishes running

app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java
Fixes https://github.com/ooni/probe/issues/1789
=> Auto test not enabled when refusing battery optimization

app/src/main/java/org/openobservatory/ooniprobe/test/test/RiseupVPN.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Signal.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Telegram.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/Whatsapp.java, app/src/sharedTest/java/org/openobservatory/ooniprobe/factory/TestKeyFactory.java
Fixes https://github.com/ooni/probe/issues/1858
=> Fix riseupvpn logic

app/src/main/java/org/openobservatory/ooniprobe/common/MKException.java, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java
Log for https://github.com/ooni/probe/issues/1328
I don't know if it makes sense.
@bassosimone can you check if it's what we want?
=> Log one more exception

README.md, app/src/main/java/org/openobservatory/ooniprobe/activity/ProxyActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManager.java, app/src/main/java/org/openobservatory/ooniprobe/common/ProxyProtocol.java, app/src/main/java/org/openobservatory/ooniprobe/common/ProxySettings.java
Fixes https://github.com/ooni/probe/issues/1904 and https://github.com/ooni/probe/issues/1905.
=> cleanups: cleanup readme.md and refactor ProxyProtocol

app/src/main/java/org/openobservatory/ooniprobe/common/ReachabilityManager.java, app/src/main/java/org/openobservatory/ooniprobe/domain/GenerateAutoRunServiceSuite.java
Fixes https://github.com/ooni/probe/issues/1896
=> don't start automated-testing if the battery level is less than 20%

app/src/main/java/org/openobservatory/ooniprobe/common/service/ServiceUtil.java
Fixes https://github.com/ooni/probe/issues/1853
=> run InstantMessagingSuite and CircumventionSuite with autorun

engine/build.gradle
Tested on my device.
See https://github.com/ooni/probe/issues/1843
=> chore: use probe-cli 3.13.0

app/src/main/java/org/openobservatory/ooniprobe/di/ApplicationModule.java
See https://github.com/ooni/probe/issues/1923 and
https://github.com/ooni/probe/issues/1922.
=> doc(android): add TODOs pointing to GH issues

.github/workflows/emulator.yml
Fixes ooni/probe#1924
- Increase emulator RAM size
=> added ram size to fix out of memory error

app/src/main/java/org/openobservatory/ooniprobe/activity/InfoActivity.java, app/src/main/res/layout/activity_info.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ca/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fa/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-id/strings.xml, app/src/main/res/values-is/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sq/strings.xml, app/src/main/res/values-sw/strings.xml, app/src/main/res/values-th/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Adds Link to OONI Blog & OONI Reports from About Page

app/src/main/java/org/openobservatory/ooniprobe/test/suite/ExperimentalSuite.java, engine/build.gradle
Reference issue: https://github.com/ooni/probe/issues/1917
Fixes: ooni/probe#1973
=> feat: add dnscheck to experimental

app/src/fdroid/java/org/openobservatory/ooniprobe/common/ThirdPartyServices.java, app/src/full/java/org/openobservatory/ooniprobe/common/ThirdPartyServices.java, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/WebConnectivity.java
Clarifies ooni/probe#1328
- Add logging statements to clarify the `MKException`
=> add log statement to clarify MKException

app/src/main/java/org/openobservatory/ooniprobe/test/suite/ExperimentalSuite.java, engine/build.gradle
Where applicable, also re-enable torsf.
See https://github.com/ooni/probe/issues/1845.
=> chore: use probe-cli 3.14.0-beta

app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/ExperimentalSuite.java, engine/build.gradle
See ooni/probe#1845
- Add proper text to experimental overview description.
=> Add proper text to experimental overview description.

app/src/main/java/org/openobservatory/ooniprobe/domain/GetTestSuite.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/Url.java, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java
Fixes ooni/probe#2012
- Change strategy to save/update urls to bulk save/update to reduce number of queries.
- ...
=> Improve performance of test startup time

app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/common/TestProgressRepository.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/ProgressFragment.java, app/src/main/java/org/openobservatory/ooniprobe/receiver/TestRunBroadRequestReceiver.java, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java
Fixes ooni/probe#2021
-  Update `TestRunBroadRequestReceiver` to publish changes to `LiveData` component which other views subscribe to.
=> improve progress bar of tests

engine/build.gradle
See https://github.com/ooni/probe/issues/1845
=> chore: use ooni/probe-cli v3.14.1

app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java
=> modified experimental card description

app/src/main/java/org/openobservatory/ooniprobe/model/database/Url.java, app/src/test/java/org/openobservatory/ooniprobe/model/database/UrlTest.java
=> update save/update logic for `Url`

app/src/main/java/org/openobservatory/ooniprobe/receiver/TestRunBroadRequestReceiver.java
Fixes https://github.com/ooni/probe/issues/2043
- Wrap access to `RunTestService` with null check
=> fix crash for website re-run

app/src/main/java/org/openobservatory/ooniprobe/di/ApplicationModule.java
Fixes https://github.com/ooni/probe/issues/1922
=> stop sending "connection: close" header to OONI backend

app/src/main/java/org/openobservatory/ooniprobe/common/service/ServiceUtil.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/ExperimentalSuite.java
Fixes https://github.com/ooni/probe/issues/2102
- Modified experimental suite to return test list based on run mode.
=> Only run `torsf` and `vanilla_tor` in unattended/background mode

app/src/main/res/values/styles.xml, app/src/main/res/values/untraslatable.xml
Related to  ooni/probe#1933
Updates #507
| .  | . |
| ----------- | ----------- |
| ![Screenshot_20220530_092929](https://user-images.githubusercontent.com/17911892/170952083-caa4d184-3a5e-400c-a2e9-937104755dbe.png) | ![Screenshot_20220530_093021](https://user-images.githubusercontent.com/17911892/170952110-c02e847d-0c22-445b-afc4-6b2d433998fa.png) |
=> Update support for in-app language selection

app/src/main/java/org/openobservatory/ooniprobe/receiver/TestRunBroadRequestReceiver.java, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java
Fixes https://github.com/ooni/probe/issues/1911
- Handle exceptions
=> Handles exception for app crashes

app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/res/values/strings.xml
=> Convey information about experimental test better

app/src/main/java/org/openobservatory/ooniprobe/activity/TextActivity.java
Fixes  https://github.com/ooni/probe/issues/2196
-  check if fragment manager is available before performing operation
=> IllegalStateException: FragmentManager has been destroyed

app/src/main/java/org/openobservatory/ooniprobe/model/database/Measurement.java
Fixes  https://github.com/ooni/probe/issues/2200
- Restructure array modification.
=> RuntimeException: An error occurred while executing doInBackground()

app/build.gradle, engine/build.gradle
See https://github.com/ooni/probe/issues/2130
=> chore: use ooni/probe-cli v3.16.x

app/build.gradle, engine/build.gradle
Let's upgrade the engine to work around the https://github.com/ooni/probe/issues/2344 issue!
=> feat: use v3.16.5

app/src/main/res/values/untraslatable.xml, app/src/main/res/xml/preferences_global.xml
Fixes https://github.com/ooni/probe/issues/2205
- removes MISC from website categories preference.
=> Different number of website categories for OONI Probe Mobile and Desktop

app/src/main/java/org/openobservatory/ooniprobe/common/service/ServiceUtil.java, app/src/main/java/org/openobservatory/ooniprobe/item/TestsuiteItem.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/PerformanceSuite.java, app/src/main/res/layout/item_seperator.xml, app/src/main/res/layout/item_testsuite.xml, app/src/main/res/values-night/colors.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
- Change the color of disabled cards
- Charge separator to text `Disabled Tests`
|.|.|
|-|-|
| ![Screenshot_20230110_224838](https://user-images.githubusercontent.com/17911892/211669984-306e826d-61d7-426e-8b7b-a4f7c1cb9b6b.png) | ![Screenshot_20230110_224911](https://user-images.githubusercontent.com/17911892/211670051-cc11ff3d-10d7-46a8-b171-db5c3ef83355.png) |
=> Modifies disabled state of test list.

app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/ProgressFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java
- Add safety check for `NPE` and `RuntimeExceptions
=> Fix: Google play priority exception

app/src/main/java/org/openobservatory/ooniprobe/common/service/RunTestService.java
Fixes https://github.com/ooni/probe/issues/2435
- Add null checks
=> Android Crash: Automated Tests: Attempt to get length of null array

app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java
Fixes https://github.com/ooni/probe/issues/2437
- Remove code checks for prevent disable of all categories.
=> Allow all tests under category to be disabled

app/src/main/java/org/openobservatory/ooniprobe/common/service/RunTestService.java
Fixes https://github.com/ooni/probe/issues/2427
- Add null checks
=> fix: NullPointerException: Attempt to invoke virtual method

app/build.gradle, app/src/main/java/org/openobservatory/ooniprobe/common/service/ServiceUtil.java
=> Updates app to release `3.8.1`

app/src/main/res/values/untraslatable.xml
Fixes  https://github.com/ooni/probe/issues/2462
- Include `MISC` removed in https://github.com/ooni/probe-android/pull/538
=> Fix: Crash on custom website list test results

app/build.gradle, engine/build.gradle
See https://github.com/ooni/probe/issues/2477
=> fix: use ooni/probe-cli v3.17.2

app/build.gradle, engine/build.gradle
See https://github.com/ooni/probe-cli/releases/tag/v3.17.5
=> chore: use ooni/probe-cli@v3.17.5

app/src/main/java/org/openobservatory/ooniprobe/common/AppDatabase.java, app/src/main/java/org/openobservatory/ooniprobe/common/service/ServiceUtil.java, app/src/sharedTest/java/org/openobservatory/ooniprobe/factory/EventResultFactory.java
- Update `EventResultFactory.buildLog` to include a log level to FIX resulting `FileNotFoundException`.
- Update tests filter to remove tests which are null before checking if component tests are empty.
=> fix: failing tests and NPE registed when starting `RunTestService`

app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/receiver/TestRunBroadRequestReceiver.java
Fixes  https://github.com/ooni/probe/issues/2454
- converted time remaining to human-readable format.
=> Fix: show remaining time as h-m-s instead of seconds.

app/build.gradle, engine/build.gradle
Part of https://github.com/ooni/probe/issues/2503
=> chore: use probe-cli v3.18.1

app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java
Fixes  https://github.com/ooni/probe/issues/2506
- Force activity to recreate after categories are updated.
=> fix: visual glitch after editing categories

app/src/main/java/org/openobservatory/ooniprobe/common/AppLogger.java, app/src/main/java/org/openobservatory/ooniprobe/test/test/AbstractTest.java, applogger/src/main/java/org/openobservatory/applogger/ILogger.kt, applogger/src/main/java/org/openobservatory/applogger/InAppLogger.kt
Closes https://github.com/ooni/probe/issues/2508#issuecomment-1647648903
=> fix(applogger): expose MK_EVENT LOG_DEBUG

.github/workflows/archive.yml
- Add a `workflow` to build APK to facilitate reviews.
=> Chore: Add `workflow` to build test apk

app/src/main/AndroidManifest.xml, app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java, app/src/main/java/org/openobservatory/ooniprobe/domain/TestDescriptorManager.java, app/src/main/java/org/openobservatory/ooniprobe/item/RunItem.java, app/src/main/java/org/openobservatory/ooniprobe/model/database/TestDescriptor.java, app/src/main/java/org/openobservatory/ooniprobe/test/suite/OONIRunSuite.java, app/src/main/res/layout/activity_measurement_detail.xml, app/src/main/res/layout/activity_overview.xml, app/src/main/res/layout/activity_result_detail.xml, engine/src/main/java/org/openobservatory/engine/OONIRunFetchResponse.kt
Related to https://github.com/ooni/probe/issues/2471
- Changed theme for `OverviewActivity`, `ResultDetailActivity`, `MeasurementDetailActivity`
- Customize `xml` with new attributes for color and animation
=> Feat OONI Run V2: Add support for `color` and `animation`

.github/workflows/build.yml, .github/workflows/emulator.yml, .github/workflows/test.yml, app/build.gradle, app/jacoco.gradle, app/src/full/java/org/openobservatory/ooniprobe/common/ThirdPartyServices.java, build.gradle, engine/build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
Reverts ooni/probe-android#583
=> Revert "Chore: Update Gradle and Android core dependencies"

app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java
=> Chore: Update `RunningActivity` to `ViewBinding`

app/build.gradle, app/src/dev/res/values/untranslatable.xml, app/src/experimental/res/values/untranslatable.xml, app/src/fdroid/res/xml/preferences_global.xml, app/src/main/res/xml/preferences_global.xml
Related to   https://github.com/ooni/probe/issues/1989
- Updates intents in preferences to target class and package for consistent behavior across various application flavors.
=> Fix: Inconsistent behavior opening preference intent screens.

app/src/main/java/org/openobservatory/ooniprobe/activity/OoniRunActivity.java
=> Chore: Update `OoniRunActivity` to use `Viewbinding`

app/src/main/java/org/openobservatory/ooniprobe/activity/CustomWebsiteActivity.java
=> Chore: Update `CustomWebsiteActivity` to `ViewBinding`

app/src/main/java/org/openobservatory/ooniprobe/activity/InfoActivity.java
=> Chore: Update `InfoActivity` to `ViewBinding`

app/src/main/java/org/openobservatory/ooniprobe/activity/ResultDetailActivity.java, app/src/main/java/org/openobservatory/ooniprobe/item/MeasurementItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/MeasurementPerfItem.java
=> Chore:  Update `ResultDetailActivity` and component fragment to use `ViewBinding`

app/src/main/java/org/openobservatory/ooniprobe/fragment/ResultListFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/resultHeader/ResultHeaderDetailFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/resultHeader/ResultHeaderMiddleboxFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/resultHeader/ResultHeaderPerformanceFragment.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/resultHeader/ResultHeaderTBAFragment.java, app/src/main/java/org/openobservatory/ooniprobe/item/CircumventionItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/ExperimentalItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/InstantMessagingItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/MiddleboxesItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/PerformanceItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/WebsiteItem.java
=> Chore: Update `ResultListFragment` and components to `ViewBinding`

NOTICE, app/build.gradle, app/src/main/java/org/openobservatory/ooniprobe/activity/MainActivity.java, app/src/main/java/org/openobservatory/ooniprobe/item/DateItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/FailedItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/SeperatorItem.java, app/src/main/java/org/openobservatory/ooniprobe/item/TextItem.java
Fixes  https://github.com/ooni/probe/issues/1709
- Remove `butterknife` dependency.
- Remove usage left in code.
=> Chore: Remove remaining references to `butterknife`

gradle/libs.versions.toml
See https://github.com/ooni/probe-cli/releases/tag/v3.19.1
=> chore: use ooni/probe-cli@v3.19.1

app/build.gradle
- Measurement engine synced with OONI Probe CLI [v3.19.1](https://github.com/ooni/probe-cli/releases/tag/v3.19.1)
- Bug fixes and Improvements
=> Release: Update app for release 3.8.5

app/src/androidTest/java/org/openobservatory/ooniprobe/ui/resultdetails/CircumventionTest.java, app/src/androidTest/java/org/openobservatory/ooniprobe/ui/resultdetails/PerformanceTest.java, app/src/androidTest/java/org/openobservatory/ooniprobe/ui/resultdetails/WebsitesTest.java, gradle.properties
-  Modified `CircumventionTest` to remove `riseupvpn` related tests since its status changed in #625
- Updated tests for ExpandableListView to use proper methods.
=> fix: failing tests

app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/overview/OverviewTestsExpandableListViewAdapter.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/overview/OverviewViewModel.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/runtests/RunTestsActivity.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/runtests/RunTestsViewModel.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/runtests/adapter/RunTestsExpandableListViewAdapter.kt, app/src/main/java/org/openobservatory/ooniprobe/common/OONIDescriptor.kt, app/src/main/java/org/openobservatory/ooniprobe/common/PreferenceManagerExtension.kt, app/src/main/java/org/openobservatory/ooniprobe/common/ReadMorePlugin.kt, app/src/main/java/org/openobservatory/ooniprobe/common/service/ServiceUtil.java, app/src/main/java/org/openobservatory/ooniprobe/fragment/DashboardFragment.kt
Fixes  https://github.com/ooni/probe/issues/2659#issuecomment-1912270537
- Update `ReadMorePlugin`  to take a `maxLength` parameter with default value `150`.
- Update `OverviewActivity` to allow modification of all automated update items.
- Update `RunTestsActivity` to save preferences only when the tests are run.
=> fix: https://github.com/ooni/probe/issues/2659#issuecomment-1912270537

app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/adddescriptor/AddDescriptorActivity.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/adddescriptor/AddDescriptorViewModel.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/overview/OverviewViewModel.kt, app/src/main/java/org/openobservatory/ooniprobe/common/OONIDescriptor.kt, app/src/main/java/org/openobservatory/ooniprobe/common/TestDescriptorManager.kt, app/src/main/java/org/openobservatory/ooniprobe/model/database/TestDescriptor.kt, app/src/main/res/layout/activity_overview.xml
Fixes # <issue>
- Adds uninstall button
- Adds setting for auto-update
- Updates preferences to properly save autorun settings
=> Feat: Update `OverviewActivity.java` interface with missing functions

app/src/main/java/org/openobservatory/ooniprobe/adapters/ResultDetailExpandableListAdapter.kt, app/src/main/res/layout/activity_result_detail.xml, app/src/main/res/layout/activity_run_tests.xml
- Update layouts to properly show `ExpandableListView` in `ResultDetailActivity` and `RunTestsActivity`
=> fix (OONI Run v2) : Hidden `ExpandableListView` section

app/build.gradle, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, gradle/libs.versions.toml
- https://github.com/ooni/probe/issues/2696
- Update to engine `v3.21.0`.
- Increment version number.
- Update translations.
=> chore: prepare release 3.8.7

app/src/main/AndroidManifest.xml, app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/adddescriptor/AddDescriptorActivity.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/overview/RevisionsView.kt, app/src/main/java/org/openobservatory/ooniprobe/activity/reviewdescriptorupdates/ReviewDescriptorUpdatesActivity.kt, app/src/main/java/org/openobservatory/ooniprobe/common/TestDescriptorManager.kt, app/src/main/java/org/openobservatory/ooniprobe/model/database/TestDescriptor.kt, app/src/main/res/layout/activity_overview.xml, app/src/main/res/layout/fragment_descriptor_update.xml, app/src/main/res/layout/fragment_revisions.xml, engine/src/main/java/org/openobservatory/engine/OONIRunDescriptor.kt, engine/src/main/java/org/openobservatory/engine/OONISession.java, engine/src/main/java/org/openobservatory/engine/PESession.java
Fixes Revision Support. Part of  https://github.com/ooni/run/issues/155
- Fetch previous revisions while fetching Descriptor.
- Display revision in `Update Review` layout
|.|.|
|-|-|
| ![Screenshot_20240410_143228](https://github.com/ooni/probe-android/assets/17911892/26a19475-a314-4a30-add5-aab47a9cc9f7) | ![Screenshot_20240410_143253](https://github.com/ooni/probe-android/assets/17911892/ef75cadd-4bb8-471c-8d71-93cf7359465e) |
=> feat (OONI Run v2): Add support for revisions.

app/src/main/java/org/openobservatory/ooniprobe/activity/overview/OverviewViewModel.kt, app/src/main/res/layout/activity_overview.xml
Fixes  https://github.com/ooni/run/issues/170
- Update XML view
|.|.|
|-|-|
| ![Screenshot_20240524_191002](https://github.com/ooni/probe-android/assets/17911892/188f02f6-fc09-4a1d-994e-45b536e3fe7f) | ![Screenshot_20240524_191038](https://github.com/ooni/probe-android/assets/17911892/98ffc464-b15b-4d33-b4f8-8b862953407c) |
=> feat: update `OverviewActivity` UI

app/src/main/java/org/openobservatory/ooniprobe/common/worker/UpdateDescriptorsWorker.kt, app/src/main/res/layout/activity_overview.xml
Fixes https://github.com/ooni/run/issues/173
- Add changes for review only when automatic update is disabled.
=> fix: install automatic updates in `ManualUpdateDescriptorsWorker` wihout review

app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/overview/OverviewTestsExpandableListViewAdapter.kt
Fixes  https://github.com/ooni/run/issues/174
- Update UI specifically for NMS
| Probe WC | Probe Run v2 Link | NMS |
|--------|--------|--------|
| ![Screenshot_20240528_161458](https://github.com/ooni/probe-android/assets/17911892/6c1c79f0-e906-44d7-9a56-9e766659290b) |  ![Screenshot_20240528_161652](https://github.com/ooni/probe-android/assets/17911892/dc98bb69-96e1-4c6b-9c9b-617a4ef23d10) | ![Screenshot_20240528_161847](https://github.com/ooni/probe-android/assets/17911892/279a5bdb-b17b-4c7b-bac4-aeeb8d965c95) |
=> fix: NMS: Further UI Tweaks to test overview screen

app/src/main/res/layout/activity_add_descriptor.xml
Fixes  https://github.com/ooni/run/issues/175
- Update layout
|.|.|
|-|-|
| ![Screenshot_20240531_115726](https://github.com/ooni/probe-android/assets/17911892/503c1c07-8977-4cf5-ac9d-87ced1d3dd5e) |  ![Screenshot_20240531_115752](https://github.com/ooni/probe-android/assets/17911892/efbe8d92-4cff-4aac-93d3-1feb35541cfc) |
=> feat: Update the install screen so layout matches revised test overview layout

app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java
- change observer for  automatic update switch.
=> fix: update events for changing state of automatic update switch

.github/workflows/validate.yml
Change when ci run is triggered
=> fix: update rules that trigger `ci` workflow

.github/workflows/validate.yml, app/build.gradle, gradle/libs.versions.toml
Fixes  https://github.com/ooni/probe/issues/2750
- Enable core library desugaring
- Update ci workflow to test on more devices
=> fix: add core library desugaring and update ci workflow to run instrumentation test on more devices

app/build.gradle
Fixes https://github.com/ooni/probe/issues/2791
-  Bump version number
=> chore: prepare for release `v3.8.9`

app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java, app/src/main/java/org/openobservatory/ooniprobe/activity/adddescriptor/AddDescriptorActivity.kt, app/src/main/java/org/openobservatory/ooniprobe/common/service/RunTestService.java, app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java, app/src/main/res/layout/activity_add_descriptor.xml, app/src/main/res/layout/activity_overview.xml, app/src/main/res/layout/activity_run_tests.xml, app/src/main/res/layout/nettest_group_list_item.xml, app/src/main/res/layout/overview_test_group_list_item.xml, app/src/main/res/layout/run_tests_child_list_item.xml, app/src/main/res/layout/run_tests_group_list_item.xml
- Update checkbox view on Overview screen, run tests and add descriptor screens
|.|.|.|
|-|-|-|
| ![Screenshot_20240823_125427](https://github.com/user-attachments/assets/e897f606-8814-402f-b532-153669518d47) | ![Screenshot_20240823_131105](https://github.com/user-attachments/assets/ffa69cc4-bdf8-42a4-8d15-851b78f118fd) | ![Screenshot_20240823_131729](https://github.com/user-attachments/assets/a96c69f7-17f2-46c9-a361-eecce96c6c98) |
=> feat: update selection items

app/src/main/java/org/openobservatory/ooniprobe/common/OONIDescriptor.kt, app/src/test/java/org/openobservatory/ooniprobe/test/suite/ExperimentalSuiteTest.java
Fixes  https://github.com/ooni/probe/issues/2795
- Add OpenVPN to experimental tests/
- Update tests to reflect change in experimental test.
|.|.|
|-|-|
| ![Screenshot_20240827_154420](https://github.com/user-attachments/assets/6fc2ceae-6966-495e-aa7f-5932fed56a82) | ![Screenshot_20240827_154432](https://github.com/user-attachments/assets/e43350e0-b25c-450e-afc5-c37bc6b97348) |
=> chore: add `openvpn` experiment to experimental card.

app/src/main/java/org/openobservatory/ooniprobe/fragment/PreferenceFragment.java
Closes https://github.com/ooni/probe/issues/2832
=> chore: add email extra to mail intent
